name: test

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

# Run "python main.py"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: ubuntu
            arch: x86_64
            runner: ubuntu-latest
          - os: ubuntu-24.04-arm
          - os: macos
            arch: x86_64
            runner: macos-13
          - os: macos
            arch: arm64
            runner: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run tests
        run: |
          python main.py